Simfish85/initial version
PostHog/calendly-app pull request #1
Opened 2022-06-30 14:19 UTC by simfish85

Created the initial version of the app

2022-06-30 16:37 UTC, kappa90 requested changes

2022-06-30 16:37 UTC, kappa90 commented on plugin.json
> +    "description": "Enriches Calendly events with additional event, owner and attendee information",
Can we make this a bit more descriptive? I had difficulty understanding what the plugin does without going through the code.

e.g. `Syncs React-Calendly event into posthog, including event, owner and attendee information`

For the rest, all good!

2022-07-01 09:37 UTC, simfish85 commented on plugin.json
> +    "description": "Enriches Calendly events with additional event, owner and attendee information",
Yes - added a better description

2022-07-01 11:38 UTC, kappa90 approved these changes

2022-07-01 11:59 UTC, merged